; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-s3-devkitc-1

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
upload_speed = 921600

board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_upload.maximum_size = 1572864
board_build.partitions = partitions_16mb_no_ota.csv
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
extra_scripts = pre:tools/pio_rom_pack.py

build_flags =
	-DBOARD_HAS_PSRAM
	-DNES_VISIBLE_HEIGHT=240
    -O3
    -Ilib/nofrendo/src
    -Ilib/nofrendo/src/cpu
    -Ilib/nofrendo/src/libsnss
    -Ilib/nofrendo/src/nes
    -Ilib/nofrendo/src/sndhrdw
    -Wno-char-subscripts
    -Wno-attributes
    -Wno-implicit-fallthrough
    -Wno-unused-function
    -Wno-unused-variable

[env:esp32-s3-devkitc-1]

[env:esp32-s3-performance]
custom_sdkconfig = file://sdkconfig.performance.defaults
